
data_file_label: SCMS_Delivery_History_Dataset.csv

training_pipeline_config:
  artifact: artifact


data_ingestion_config:
  data_base: Shipment_Pricing
  collection_name: Data
  artifact_dir: data_ingestion
  raw_data_dir: raw_data
  train_test_split : 0.2
  ingested_dir: ingested_Data
  ingested_train_dir: Train
  ingested_test_dir: Test


data_validation_config:
  data_validation_dir: data_validation
  validated_data: validated_data
  Train_data: Train
  Test_data: Test



data_transformation_config:
  data_transformation_dir: data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessor
  preprocessed_object_file_name: preprocessed.pkl
  feature_eng_file: fea_eng.pkl

model_trainer_config:
  model_training: model_training 
  model_object: model.pkl
  model_report: report.yaml
  mlflow:
    Run_name: Trial
    Experiment: Experiment_01

param_optimize_config:
  param_optimize_dir: param_optimize_dir
  model_object: model.pkl
  model_report: report.yaml

model_eval_config:
  model_eval_dir: model_evaluation
  model_object: model.pkl
  model_report: report.yaml


saved_model_config:
  directory: Saved_model
  model_object: model.pkl
  model_report : report.yaml

Prediction:
  prediction_object_directory: preprocessor
  batch_prediction:
    directory: batch_prediction
    prediction_folder: prediction
    upload_directory: uploaded_csv
    prediction_csv: prediction.csv
  mongo_prediction:
    collection_label: prediction