
data_file_label: SCMS_Delivery_History_Dataset.csv

training_pipeline_config:
  pipeline_name: project_artifact
  artifact_dir: artifact

data_ingestion_config:
  data_base: Shipment_pricing
  collection_name: Data
  data_ingestion: data_ingestion
  raw_data_dir: raw_data
  train_test_split : 0.2
  ingested_dir: ingested_Data
  ingested_train_dir: Train
  ingested_test_dir: Test

data_transformation_config:
  data_transformation_dir: data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  feature_eng_file: fea_eng.pkl

model_trainer_config:
  model_training: model_training 
  model_object: model.pkl
  model_report: report.yaml
  mlflow:
    run_id: Trial
    experiment: Experiment_01

saved_model_config:
  directory: Saved_model
  model_object: model.pkl
  report : report.yaml

Prediction:
  prediction_object_directory: prediction_files
  batch_prediction:
    directory: batch_prediction
    prediction_folder: prediction
    upload_directory: uploaded_csv
    prediction_csv: prediction.csv
  mongo_prediction:
    collection_label: prediction